package dev.orderflow.order.order;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * An order: a few lines, a customer, a status, and a total that was agreed at placement time.
 *
 * <p>State changes go through {@link #confirm()}, {@link #cancel(String)} and {@link #ship()},
 * which refuse an illegal transition. That refusal is the mechanism that makes the saga safe
 * against duplicate events (Session 09): the second {@code PaymentSucceeded} cannot confirm an
 * order that is already CONFIRMED, so no second event is emitted.</p>
 */
@Entity
@Table(name = "orders")
public class Order {

    @Id
    private UUID id;

    @Column(name = "customer_id", nullable = false, length = 64)
    private String customerId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private OrderStatus status;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal total;

    @Column(name = "cancellation_reason", length = 200)
    private String cancellationReason;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<OrderLine> lines = new ArrayList<>();

    @Version
    private long version;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected Order() {
    }

    private Order(UUID id, String customerId) {
        this.id = id;
        this.customerId = customerId;
        this.status = OrderStatus.PENDING;
        this.total = BigDecimal.ZERO;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    /**
     * Creates a pending order.
     *
     * @param id    generated by the caller <b>before</b> the catalog is contacted, so the same id
     *              can be used as the idempotency key of the reservation (Session 05)
     * @param total priced by the catalog, which owns prices
     */
    public static Order pending(UUID id, String customerId, List<NewLine> newLines, BigDecimal total) {
        Order order = new Order(id, customerId);
        for (NewLine line : newLines) {
            order.lines.add(new OrderLine(order, line.sku(), line.quantity(), line.unitPrice()));
        }
        order.total = total;
        return order;
    }

    /** A line as supplied by the application layer, before it becomes an entity. */
    public record NewLine(String sku, int quantity, BigDecimal unitPrice) {
    }

    public void confirm() {
        transitionTo(OrderStatus.CONFIRMED);
    }

    public void ship() {
        transitionTo(OrderStatus.SHIPPED);
    }

    public void cancel(String reason) {
        transitionTo(OrderStatus.CANCELLED);
        this.cancellationReason = reason;
    }

    private void transitionTo(OrderStatus next) {
        if (!status.canMoveTo(next)) {
            throw new IllegalOrderTransitionException(id, status, next);
        }
        this.status = next;
        this.updatedAt = Instant.now();
    }

    /** True when the order is already in this state; used to make event handling idempotent. */
    public boolean isIn(OrderStatus candidate) {
        return status == candidate;
    }

    public UUID getId() {
        return id;
    }

    public String getCustomerId() {
        return customerId;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public List<OrderLine> getLines() {
        return List.copyOf(lines);
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
